[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"
ignore = [
  # FIXME: Potential segfault in `localtime_r` invocations
  "RUSTSEC-2020-0159",

  # FIXME: Potential segfault in the time crate
  "RUSTSEC-2020-0071",

  # FIXME: Data race when sending and receiving after closing a `oneshot` channel
  "RUSTSEC-2021-0124",

  # FIXME: `net2` crate has been deprecated; use `socket2` instead
  "RUSTSEC-2020-0016",

  # FIXME: Some lock_api lock guard objects can cause data races
  "RUSTSEC-2020-0070",
]

[bans]
multiple-versions = "allow"
wildcards = "warn"

# `rustls` should be used instead.
[[bans.deny]]
name = "openssl"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
unlicensed = "warn"
copyleft = "deny"
default = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.8
allow = [
  "MIT",
  "Apache-2.0",
  "Unlicense",
  "Zlib",
  "MPL-2.0",
  "ISC",
  "BSD-2-Clause",
  "BSD-3-Clause",
]
exceptions = [
  { allow = ["ISC", "MIT", "OpenSSL"], name = "ring", version = "*" },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "encoding_rs"
expression = "Apache-2.0 AND BSD-3-Clause"
license-files = [
  { path = "COPYRIGHT", hash = 972598577 },
]
