# Dependencies

## NOTE: Ensure you keep in sync with the CI version
[tasks.cargo-nextest]
install_crate = { crate_name = "cargo-nextest", version = "0.9" }

[tasks.cargo-audit]
install_crate = { crate_name = "cargo-audit" }

[tasks.cargo-deny]
install_crate = { crate_name = "cargo-deny" }

## NOTE: Ensure you keep in sync with `sqlx` crate version
[tasks.sqlx-cli]
install_crate = { crate_name = "sqlx-cli", version = "0.5" }

# Tasks
[tasks.unit]
command = "cargo"
args = ["nextest", "run", "--lib", "--bins"]
dependencies = ["cargo-nextest"]

[tasks.integration]
command = "cargo"
args = ["nextest", "run", "--test", "*"]
dependencies = ["cargo-nextest", "sql-migrate"]

[tasks.test]
dependencies = [
  "unit",
  "integration",
]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt-ci]
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--tests"]

[tasks.lint]
dependencies = [
  "check",
  "fmt",
  "clippy",
]

[tasks.lint-ci]
dependencies = [
  "check",
  "fmt-ci",
  "clippy",
]

[tasks.sql-migrate]
command = "cargo"
args = ["run", "--bin", "throwaway-migrate"]

[tasks.sql-prepare]
env = { "DATABASE_URL" = "postgresql://postgres:password@localhost:5432/postgres"}
command = "cargo"
args = ["sqlx", "prepare", "--", "--lib"]
dependencies = ["sqlx-cli"]

[tasks.sql]
dependencies = [
  "sql-migrate",
  "sql-prepare",
]

[tasks.audit]
command = "cargo"
args = ["audit"]
dependencies = ["cargo-audit"]

[tasks.deny]
command = "cargo"
args = ["deny", "check"]
dependencies = ["cargo-deny"]

[tasks.security]
dependencies = [
  "audit",
  "deny",
]

[tasks.verify]
dependencies = [
  "sql",
  "build",
  "lint",
  "security",
  "test",
]

[tasks.ci]
dependencies = [
  "build",
  "lint-ci",
  "security",
  "test",
]
