edition = "2021"
unstable_features = true

combine_control_expr = false
comment_width = 120
condense_wildcard_suffixes = true
chain_width = 40
force_multiline_blocks = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
max_width = 120
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
spaces_around_ranges = true
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
report_fixme = "Never"
report_todo = "Never"
