[toolchain]
channel = "nightly-2022-02-28"
components = ["cargo", "rustfmt", "clippy", "rust-src", "rust-std"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu",
]
