---
name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build package
        run: nix develop --command ./scripts/compile.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run formatter
        run: nix develop --command ./scripts/fmt-ci.sh

      - name: Run linters
        run: nix develop --command ./scripts/lint.sh

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run unit tests
        run: nix develop --command ./scripts/test/unit.sh

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Create cluster
        run: nix develop --command ./scripts/cluster/up.sh

      - name: Provision DB
        run: nix develop --command ./scripts/sql/migrate.sh

      - name: Run integration tests
        run: nix develop --command ./scripts/test/integration.sh
