---
name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  RUST_VERSION: "nightly-2022-03-10"
  RUST_LOG: "debug"
  CARGO_INCREMENTAL: "true"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Build package
        run: ./scripts/compile.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Run linters
        run: ./scripts/fmt-ci.sh && ./scripts/lint.sh

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          version: "0.9"

      - name: Run unit tests
        run: ./scripts/test/unit.sh

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Terraform repository
        uses: actions/checkout@v3
        with:
          repository: CathalMullan/throwaway-terraform
          path: throwaway-terraform

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Install sqlx-cli
        uses: baptiste0928/cargo-install@v1
        with:
          crate: sqlx-cli
          version: "0.5.11"

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          version: "0.9"

      - name: Create cluster
        uses: ./.github/actions/throwaway-cluster

      - name: Provision DB
        run: ./scripts/sql/migrate.sh

      - name: Run integration tests
        run: ./scripts/test/integration.sh
