---
name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.rs'

env:
  RUST_VERSION: "nightly"
  RUST_LOG: "debug"
  CARGO_INCREMENTAL: "true"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Build package
        run: cargo build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Install cargo-make
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-make

      - name: Run linters
        run: cargo make lint-ci

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Install cargo-make
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-make

      - name: Run unit tests
        run: cargo make unit

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout Terraform repository
        uses: actions/checkout@v2
        with:
          repository: CathalMullan/throwaway-terraform
          path: throwaway-terraform

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Install cargo-make
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-make

      - name: Create cluster
        uses: ./.github/actions/throwaway-cluster

      - name: Run integration tests
        run: cargo make integration
