---
name: Coverage

on:
  workflow_dispatch:

env:
  RUST_VERSION: "nightly-2022-03-10"
  RUST_LOG: "debug"
  CARGO_INCREMENTAL: "true"

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Terraform repository
        uses: actions/checkout@v3
        with:
          repository: CathalMullan/throwaway-terraform
          path: throwaway-terraform

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ env.RUST_VERSION }}"

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v1

      - name: Install sqlx-cli
        uses: baptiste0928/cargo-install@v1
        with:
          crate: sqlx-cli
          version: "0.5.11"

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          version: "0.9"

      - name: Create cluster
        uses: ./.github/actions/throwaway-cluster

      - name: Provision DB
        run: ./scripts/sql/migrate.sh
        env:
          DATABASE_URL: "postgresql://postgres:password@localhost:5432/postgres"

      - name: Run cargo tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          out-type: Html

      - name: Move coverage report
        run: |
          mkdir -p build
          mv tarpaulin-report.html build/index.html

      - name: Deploy coverage report
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: coverage-pages
          folder: build
