---
name: Coverage

on:
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Create cluster
        run: nix develop --command ./scripts/cluster/up.sh

      - name: Provision DB
        run: nix develop --command ./scripts/sql/migrate.sh

      - name: Generate coverage
        run: nix develop --command ./scripts/coverage.sh

      - name: Deploy coverage report
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: coverage-pages
          folder: build
