---
name: Nix

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '*.nix'
  push:
    branches:
      - master
    paths:
      - '*.nix'

defaults:
  run:
    shell: nix develop --verbose --command bash {0}

jobs:
  nix-e2e:
    name: Nix E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://releases.nixos.org/nix/nix-2.7.0/install
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build Nix shell
        run: echo 'Nix shell built.'

      - name: Create cluster
        run: ./scripts/cluster/up.sh

      - name: Build package
        run: ./scripts/compile.sh

      - name: Provision DB
        run: ./scripts/sql/migrate.sh

      - name: Build package
        run: ./scripts/compile.sh

      - name: Run unit tests
        run: ./scripts/test/unit.sh

      - name: Run integration tests
        run: ./scripts/test/integration.sh
