---
name: Nix

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  throwaway:
    name: throwaway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cacheID: build
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build throwaway
        run: nix build --print-build-logs .#throwaway

#  throwawayZig:
#    name: throwawayZig
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        with:
#          submodules: true
#
#      - name: Bootstrap CI
#        uses: ./.github/actions/ci-bootstrap
#        with:
#          cacheID: build
#          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
#
#      - name: Build throwawayZig
#        run: nix build --print-build-logs .#throwawayZig

  throwawayNixImage:
    name: throwawayNixImage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cacheID: build
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build throwawayNixImage
        run: nix build --print-build-logs .#throwawayNixImage

#  throwawayDevImage:
#    name: throwawayDevImage
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        with:
#          submodules: true
#
#      - name: Bootstrap CI
#        uses: ./.github/actions/ci-bootstrap
#        with:
#          cacheID: build
#          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
#
#      - name: Build throwawayDevImage
#        run: nix build --print-build-logs .#throwawayDevImage
