---
name: Nix

on:
  workflow_dispatch:

jobs:
  nix-develop:
    name: Nix Develop
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://releases.nixos.org/nix/nix-2.7.0/install
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build package
        run: nix develop --command ./scripts/compile.sh
