---
name: Nix

on:
  workflow_dispatch:

jobs:
  nix-e2e:
    name: Nix E2E
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://releases.nixos.org/nix/nix-2.7.0/install
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build package
        run: nix develop --command ./scripts/compile.sh

      - name: Create cluster
        uses: ./.github/actions/throwaway-cluster

      - name: Provision DB
        run: nix develop --command ./scripts/sql/migrate.sh

      - name: Build package
        run: nix develop --command ./scripts/compile.sh

      - name: Run unit tests
        run: nix develop --command ./scripts/test/unit.sh

      - name: Run integration tests
        run: nix develop --command ./scripts/test/integration.sh
