---
name: Security

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # At 12:00 on Wednesday
    - cron: '0 12 * * 3'

defaults:
  run:
    shell: nix develop --ignore-environment --command bash {0}

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run audit
        run: ./scripts/security/audit.sh

  deny:
    name: Deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Bootstrap CI
        uses: ./.github/actions/ci-bootstrap
        with:
          cachixToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run deny
        run: ./scripts/security/deny.sh
